apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
  namespace: default
type: Opaque
data:
  # BOT_TOKEN закодированный в base64
  # Замените на ваш реальный токен: echo -n "ваш_токен" | base64
  BOT_TOKEN: NzU1MTEzODA5MzpBQUVSX1FESnBQNHcyd2I2Z3hrWGc1MktKYVd1WGxPTEt3UQ==